[package]
name = "blockchain-project"
version = "0.1.0"
authors = ["garritfra <garritfranke@gmail.com>"]

[dependencies]
rust-crypto = "0.2.36"
serde_derive = "1.0.34"
bincode = "1.0.0"
serde = "1.0.34"
bytebuffer = "0.2.1"